name: Restart Cloudtype App

on:
  schedule:
    # 매일 한국시간 오후 1시에 실행 (UTC 4시)
    - cron: '0 4 * * *'
  workflow_dispatch:  # 수동 실행도 허용

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Cloudtype App
        run: |
          curl -X POST https://api.cloudtype.io/api/v1/apps/page1762/naver-geocode-proxy/deploy \
            -H "Authorization: Bearer ${{ secrets.CLOUDTYPE_API_TOKEN }}"
